I've found a issue at "tunnel.on('error', ...".
Hi.
118 line, writeBufferedLog's third parameter is missing.
When call "writeBufferedLog", third argument what "fn" is must passed.
Otherwise it occur "Fatal error: undefined is not a function".